### ISSUE TITLE
AttributeError: 'V1Secret' object has no attribute 'binary_data' 

### ISSUE THREAD

**Issue by languitar** [kiwigrid/k8s-sidecar#110]
We are using this sidecar through the Grafana chart. Today, Grafana dind't start anymore. The sidecar fails when starting to process the first secret (not configmap):

```
 grafana-sc-notifiers [2021-02-19 11:53:22] Contents of cm-notifier.yaml haven't changed. Not overwriting existing file                       grafana-sc-notifiers Traceback (most recent call last):                                                                                     
 grafana-sc-notifiers   File "/app/sidecar.py", line 73, in <module>                                                                          grafana-sc-notifiers     main()                                                                                                              grafana-sc-notifiers   File "/app/sidecar.py", line 65, in main                                                                             
 grafana-sc-notifiers     listResources(label, labelValue, targetFolder, url, method, payload,                                                grafana-sc-notifiers   File "/app/resources.py", line 110, in listResources                                                                  grafana-sc-notifiers     if sec.binary_data is not None:                                                                                    
 grafana-sc-notifiers AttributeError: 'V1Secret' object has no attribute 'binary_data'      
```

Secrets do not have a `binary_data` attribute: https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Secret.md. The code probably shouldn't check this for secrets.

**Comment by monotek** [comment]
Grafana chart will be fixed with: https://github.com/grafana/helm-charts/pull/234

**Comment by languitar** [comment]
That was quick! Thanks!
