### ISSUE TITLE
`IGNORE_ALREADY_PROCESSED` fails on EKS 1.21

### ISSUE THREAD

**Issue by ccodreanu** [kiwigrid/k8s-sidecar#188]
Hi!

I wanted to report an issue with the 1.18.0 version and specifically with the flag in title.

When running on EKS 1.21 the container errors out due to:

```
Traceback (most recent call last):
  File "/app/sidecar.py", line 142, in <module>
    main()
  File "/app/sidecar.py", line 82, in main
    if int(version.major) > 1 or (int(version.major) == 1 and int(version.minor) >= 19):
ValueError: invalid literal for int() with base 10: '21+'
```

Thanks!

**Comment by jekkel** [comment]
@ccodreanu Can you please post the output of
```
kubectl version --output=yaml
```

@otchilin You probably want to have look into this?

**Comment by ccodreanu** [comment]
> @ccodreanu Can you please post the output of
> 
> ```
> kubectl version --output=yaml
> ```

```
clientVersion:
  buildDate: "2021-11-17T15:48:33Z"
  compiler: gc
  gitCommit: b695d79d4f967c403a96986f1750a35eb75e75f1
  gitTreeState: clean
  gitVersion: v1.22.4
  goVersion: go1.16.10
  major: "1"
  minor: "22"
  platform: darwin/amd64
serverVersion:
  buildDate: "2022-02-17T16:36:28Z"
  compiler: gc
  gitCommit: eb09fc479c1b2bfcc35c47416efb36f1b9052d58
  gitTreeState: clean
  gitVersion: v1.21.9-eks-0d102a7
  goVersion: go1.16.12
  major: "1"
  minor: 21+
  platform: linux/amd64

**Comment by jekkel** [comment]
@ccodreanu please test with [v1.18.1](https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.18.1)
