### ISSUE TITLE
Crash: argument of type 'ApiException' is not iterable

### ISSUE THREAD

**Issue by flands** [kiwigrid/k8s-sidecar#26]
After #15 I often get:

```
Traceback (most recent call last):
  File "/app/sidecar.py", line 168, in main
    watchForChanges(label, targetFolder, url, method, payload, namespace, folderAnnotation)
  File "/app/sidecar.py", line 99, in watchForChanges
    for event in stream:
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 128, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Sun, 10 Mar 2019 19:29:47 GMT', 'Content-Length': '186'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sidecar.py", line 181, in <module>
    main()
  File "/app/sidecar.py", line 170, in main
    if "500" not in e:
TypeError: argument of type 'ApiException' is not iterable
```

**Comment by Tim-Smyth** [comment]
Version 0.0.13 should have fixed that. Are you sure you have a current version running?
