### ISSUE TITLE
Sidecar v0.0.18 crashes with API Server Error

### ISSUE THREAD

**Issue by oivfarafontov** [kiwigrid/k8s-sidecar#37]
The sidecar v0.0.18 periodically crashes with the following error

```Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/app/resources.py", line 120, in _watch_resource_loop
    _watch_resource_iterator(*args)
  File "/app/resources.py", line 82, in _watch_resource_iterator
    for event in stream:
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 128, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 15 Jul 2019 18:17:16 GMT', 'Content-Length': '186'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'

Process for configmap died. Stopping and exiting
Traceback (most recent call last):
  File "/app/sidecar.py", line 54, in <module>
    main()
  File "/app/sidecar.py", line 50, in main
    payload, namespace, folderAnnotation, resources)
  File "/app/resources.py", line 155, in watchForChanges
    raise Exception("Loop died")
Exception: Loop died

**Comment by Eurymone** [comment]
Getting the same error with the same version.

**Comment by mitchellmaler** [comment]
Getting the same error

```
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/app/resources.py", line 120, in _watch_resource_loop
    _watch_resource_iterator(*args)
  File "/app/resources.py", line 82, in _watch_resource_iterator
    for event in stream:
  File "/usr/local/lib/python3.7/site-packages/kubernetes/watch/watch.py", line 128, in stream
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 26 Jul 2019 20:09:28 GMT', 'Content-Length': '186'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'

Process for configmap died. Stopping and exiting
Traceback (most recent call last):
  File "/app/sidecar.py", line 54, in <module>
    main()
  File "/app/sidecar.py", line 50, in main
    payload, namespace, folderAnnotation, resources)
  File "/app/resources.py", line 163, in watchForChanges
    raise Exception("Loop died")
Exception: Loop died
```

**Comment by cscheib** [comment]
I've seen similar issues, but it's not been bad enough for me to take action.  subscribing to this issue.

**Comment by rince86** [comment]
I am also experiencing the same issue and grafana pod stays in crash loop as a result:

`prometheus-grafana-67c47469cb-fwm82                      1/2     CrashLoopBackOff   160        16h
`

**Comment by aeugenio** [comment]
we are seeing the same behavior in 5 eks clusters.

**Comment by Tim-Smyth** [comment]
Hi everyone. Could you please tell me which k8s version you are using?
Also the new version 0.1.20 uses the current kubernetes client and supports every version up to 1.14 ( [client](https://github.com/kubernetes-client/python) ). 
The new build pipeline runs some basic tests against k8s version 1.11 - 1.14, so basic errors should emerge there.
Looking forward to hearing from you

**Comment by rince86** [comment]
Hello @Tim-Smyth, I am using 1.13.4 version of k8s.
Also I need to mention that after downgrading image to v0.0.17 the problem did not occurred again.

**Comment by aeugenio** [comment]
kube: v1.12.10-eks-2e569f
prom-operator: 6.4.0

**Comment by livingeek** [comment]
> kube: v1.12.10-eks-2e569f
> prom-operator: 6.4.0

Of note running these with an older version of the sidecar didn't seem to fix issues with the restarts.  We tried two additional versions and still saw hourly crashes.

**Comment by chuck-ecob** [comment]
kube: v1.13.7-gke.8
prom-operator: 6.6.1

**Comment by dmyerscough** [comment]
I am running k8s version: `v1.13.7-gke.8`

I built from master and haven't seen the restart happen.
