### ISSUE TITLE
sidecar version 0.5.0 crashes with API Server Error. Which version is stable for this issue?

### ISSUE THREAD

**Issue by ShileiGuo** [kiwigrid/k8s-sidecar#46]
log is DEPRECATED and will be removed in a future version. Use logs instead.
/usr/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Starting config map collector
Config for cluster api loaded...
Traceback (most recent call last):
  File "sidecar.py", line 96, in <module>
    main()
  File "sidecar.py", line 92, in main
    watchForChanges(label, targetFolder, url, method, payload)
  File "sidecar.py", line 51, in watchForChanges
    for event in stream:
  File "/usr/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 128, in stream
    resp = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11854, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11957, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Audit-Id': '335c1795-27f0-49b5-8020-2a16ba5a8fc9', 'Content-Type': 'application/json', 'Date': 'Mon, 26 Aug 2019 15:40:03 GMT', 'Content-Length': '186'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'

**Comment by ShileiGuo** [comment]
I found the same issue in closed ticket, if it is solved in the version 0.13.0?
Thank,

**Comment by jekkel** [comment]
I think the issue is solved already. Please reopen if not.
