### ISSUE TITLE
Sidecar crashes with IncompleteRead

### ISSUE THREAD

**Issue by clalbus** [kiwigrid/k8s-sidecar#5]
**Sidecar version:** Issue has been observed on 0.0.3 and 0.0.5
**Kubernetes version:** 1.10.6 (AKS)

I am running Grafana (using helm stable release) with sidecar for datasources/dashboards ([relevant docs](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards))

After some time sidecar starts to crash (in a loop) with the following errors from the logs:

```
Starting config map collector
Config for cluster api loaded...
Working on configmap kube-system/xxx-grafana.v2
Working on configmap kube-system/xxx-grafana.v4
Working on configmap kube-system/xxx-grafana.v5
Working on configmap kube-system/xxx-grafana.v6
Working on configmap kube-system/addon-http-application-routing-tcp-services
Working on configmap kube-system/addon-http-application-routing-udp-services
Working on configmap kube-system/dashboards.v2
Working on configmap kube-system/xxx-grafana.v1
Working on configmap default/xxx-grafana-config-dashboards
Working on configmap kube-system/addon-http-application-routing-nginx-configuration
Working on configmap kube-system/omsagent-rs-config
Working on configmap kube-system/azureproxy-nginx
Working on configmap default/xxx-prometheus-server
Working on configmap kube-system/api.v1
Working on configmap kube-system/dashboards.v7
Working on configmap kube-system/dashboards.v1
Working on configmap kube-system/dashboards.v5
Working on configmap kube-system/image-storage.v1
Working on configmap kube-system/kubedns-kubecfg
Working on configmap kube-system/xxx-grafana.v3
Working on configmap default/api-grafana-dashboard
Configmap with label found
File in configmap api-dashboard.json ADDED
Working on configmap default/xxx-grafana
Working on configmap kube-system/azureproxy-config
Working on configmap kube-system/dashboards.v6
Working on configmap kube-system/xxx-prometheus.v1
Working on configmap kube-system/render.v1
Working on configmap default/prometheus-grafana-datasource
Working on configmap default/render-grafana-dashboard
Configmap with label found
File in configmap render-dashboard.json ADDED
Working on configmap default/xxx-prometheus-alertmanager
Working on configmap kube-system/dashboards.v3
Working on configmap kube-system/dashboards.v4
Working on configmap kube-system/heapster-config
Working on configmap default/image-storage-grafana-dashboard
Configmap with label found
File in configmap image-storage-dashboard.json ADDED
Working on configmap default/xxx-lb-traefik
Working on configmap kube-system/xxx-lb.v1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 572, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 331, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 637, in read_chunked
    self._update_chunk_length()
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 576, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sidecar.py", line 96, in <module>
    main()
  File "/app/sidecar.py", line 92, in main
    watchForChanges(label, targetFolder, url, method, payload)
  File "/app/sidecar.py", line 51, in watchForChanges
    for event in stream:
  File "/usr/local/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 124, in stream
    for line in iter_resp_lines(resp):
  File "/usr/local/lib/python3.6/site-packages/kubernetes/watch/watch.py", line 45, in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 665, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 349, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

The exception occurs at different points in time i.e. not always after processing the same ConfigMap.

Please let me know if you require any other information.

**Comment by eloo** [comment]
On my setup it also looks like the side is crashing from time to time.. But i didn't see such logs.. 
I only see that the sidecar was restarted (15 - 20 times in around 18 hours)

any ideas how to fix this?
Thx

**Comment by eloo** [comment]
i've greated a small PR where i simply loop over a try-except block to keep the sidecar running...
what do you think?

**Comment by Tim-Smyth** [comment]
Hello and sorry for delay.
I too have the issue that the connection to the k8s api fails from time to time, but my rate is far lower (eg 7 restarts in 5 days). @clalbus does your cluster experience any unusual high load? Does your sidecar container keep on crashing right away after an initial delay?

**Comment by vsliouniaev** [comment]
Looks like another similar issue reported here: https://github.com/helm/charts/issues/9136

**Comment by Tim-Smyth** [comment]
Exception handling was improved in PR #15 Please try if the problem still occurs with the current version
